// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

public final class Bar {
  private Bar() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waiter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waiter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbar.proto\"\226\001\n\004meal\022\n\n\002id\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\r\n\005price\030\003 \001(\002\022\024\n\014prepare_time\030\004 " +
      "\001(\005\022\023\n\013deliverable\030\005 \001(\010\":\n\004type\022\r\n\tBREA" +
      "KFAST\020\000\022\n\n\006DINNER\020\001\022\013\n\007DESSERT\020\002\022\n\n\006SUPP" +
      "ER\020\003\"t\n\006client\022\n\n\002id\030\001 \001(\005\022\024\n\005meals\030\002 \003(" +
      "\0132\005.meal\022\014\n\004bill\030\003 \001(\002\":\n\014satisfaction\022\010" +
      "\n\004POOR\020\000\022\013\n\007AVERAGE\020\001\022\010\n\004GOOD\020\002\022\t\n\005GREAT" +
      "\020\003\"<\n\006waiter\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\030" +
      "\n\007clients\030\003 \003(\0132\007.clientB/\n+server.src.m" +
      "ain.java.pl.afornalik.bar.modelP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meal_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", "PrepareTime", "Deliverable", });
    internal_static_client_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_descriptor,
        new java.lang.String[] { "Id", "Meals", "Bill", });
    internal_static_waiter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waiter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waiter_descriptor,
        new java.lang.String[] { "Id", "Name", "Clients", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
