// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

/**
 * Protobuf type {@code client}
 */
public final class client extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client)
    clientOrBuilder {
private static final long serialVersionUID = 0L;
  // Use client.newBuilder() to construct.
  private client(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private client() {
    meals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new client();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private client(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              meals_ = new java.util.ArrayList<server.src.main.java.pl.afornalik.bar.model.meal>();
              mutable_bitField0_ |= 0x00000001;
            }
            meals_.add(
                input.readMessage(server.src.main.java.pl.afornalik.bar.model.meal.parser(), extensionRegistry));
            break;
          }
          case 29: {

            bill_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        meals_ = java.util.Collections.unmodifiableList(meals_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_client_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_client_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            server.src.main.java.pl.afornalik.bar.model.client.class, server.src.main.java.pl.afornalik.bar.model.client.Builder.class);
  }

  /**
   * Protobuf enum {@code client.satisfaction}
   */
  public enum satisfaction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>POOR = 0;</code>
     */
    POOR(0),
    /**
     * <code>AVERAGE = 1;</code>
     */
    AVERAGE(1),
    /**
     * <code>GOOD = 2;</code>
     */
    GOOD(2),
    /**
     * <code>GREAT = 3;</code>
     */
    GREAT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>POOR = 0;</code>
     */
    public static final int POOR_VALUE = 0;
    /**
     * <code>AVERAGE = 1;</code>
     */
    public static final int AVERAGE_VALUE = 1;
    /**
     * <code>GOOD = 2;</code>
     */
    public static final int GOOD_VALUE = 2;
    /**
     * <code>GREAT = 3;</code>
     */
    public static final int GREAT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static satisfaction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static satisfaction forNumber(int value) {
      switch (value) {
        case 0: return POOR;
        case 1: return AVERAGE;
        case 2: return GOOD;
        case 3: return GREAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<satisfaction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        satisfaction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<satisfaction>() {
            public satisfaction findValueByNumber(int number) {
              return satisfaction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return server.src.main.java.pl.afornalik.bar.model.client.getDescriptor().getEnumTypes().get(0);
    }

    private static final satisfaction[] VALUES = values();

    public static satisfaction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private satisfaction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:client.satisfaction)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int MEALS_FIELD_NUMBER = 2;
  private java.util.List<server.src.main.java.pl.afornalik.bar.model.meal> meals_;
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  @java.lang.Override
  public java.util.List<server.src.main.java.pl.afornalik.bar.model.meal> getMealsList() {
    return meals_;
  }
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends server.src.main.java.pl.afornalik.bar.model.mealOrBuilder> 
      getMealsOrBuilderList() {
    return meals_;
  }
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  @java.lang.Override
  public int getMealsCount() {
    return meals_.size();
  }
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  @java.lang.Override
  public server.src.main.java.pl.afornalik.bar.model.meal getMeals(int index) {
    return meals_.get(index);
  }
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  @java.lang.Override
  public server.src.main.java.pl.afornalik.bar.model.mealOrBuilder getMealsOrBuilder(
      int index) {
    return meals_.get(index);
  }

  public static final int BILL_FIELD_NUMBER = 3;
  private float bill_;
  /**
   * <code>float bill = 3;</code>
   * @return The bill.
   */
  @java.lang.Override
  public float getBill() {
    return bill_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    for (int i = 0; i < meals_.size(); i++) {
      output.writeMessage(2, meals_.get(i));
    }
    if (bill_ != 0F) {
      output.writeFloat(3, bill_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    for (int i = 0; i < meals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, meals_.get(i));
    }
    if (bill_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, bill_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof server.src.main.java.pl.afornalik.bar.model.client)) {
      return super.equals(obj);
    }
    server.src.main.java.pl.afornalik.bar.model.client other = (server.src.main.java.pl.afornalik.bar.model.client) obj;

    if (getId()
        != other.getId()) return false;
    if (!getMealsList()
        .equals(other.getMealsList())) return false;
    if (java.lang.Float.floatToIntBits(getBill())
        != java.lang.Float.floatToIntBits(
            other.getBill())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (getMealsCount() > 0) {
      hash = (37 * hash) + MEALS_FIELD_NUMBER;
      hash = (53 * hash) + getMealsList().hashCode();
    }
    hash = (37 * hash) + BILL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBill());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static server.src.main.java.pl.afornalik.bar.model.client parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(server.src.main.java.pl.afornalik.bar.model.client prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code client}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client)
      server.src.main.java.pl.afornalik.bar.model.clientOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_client_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.src.main.java.pl.afornalik.bar.model.client.class, server.src.main.java.pl.afornalik.bar.model.client.Builder.class);
    }

    // Construct using server.src.main.java.pl.afornalik.bar.model.client.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMealsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      if (mealsBuilder_ == null) {
        meals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        mealsBuilder_.clear();
      }
      bill_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_client_descriptor;
    }

    @java.lang.Override
    public server.src.main.java.pl.afornalik.bar.model.client getDefaultInstanceForType() {
      return server.src.main.java.pl.afornalik.bar.model.client.getDefaultInstance();
    }

    @java.lang.Override
    public server.src.main.java.pl.afornalik.bar.model.client build() {
      server.src.main.java.pl.afornalik.bar.model.client result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public server.src.main.java.pl.afornalik.bar.model.client buildPartial() {
      server.src.main.java.pl.afornalik.bar.model.client result = new server.src.main.java.pl.afornalik.bar.model.client(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (mealsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          meals_ = java.util.Collections.unmodifiableList(meals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.meals_ = meals_;
      } else {
        result.meals_ = mealsBuilder_.build();
      }
      result.bill_ = bill_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof server.src.main.java.pl.afornalik.bar.model.client) {
        return mergeFrom((server.src.main.java.pl.afornalik.bar.model.client)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(server.src.main.java.pl.afornalik.bar.model.client other) {
      if (other == server.src.main.java.pl.afornalik.bar.model.client.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (mealsBuilder_ == null) {
        if (!other.meals_.isEmpty()) {
          if (meals_.isEmpty()) {
            meals_ = other.meals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMealsIsMutable();
            meals_.addAll(other.meals_);
          }
          onChanged();
        }
      } else {
        if (!other.meals_.isEmpty()) {
          if (mealsBuilder_.isEmpty()) {
            mealsBuilder_.dispose();
            mealsBuilder_ = null;
            meals_ = other.meals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            mealsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMealsFieldBuilder() : null;
          } else {
            mealsBuilder_.addAllMessages(other.meals_);
          }
        }
      }
      if (other.getBill() != 0F) {
        setBill(other.getBill());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      server.src.main.java.pl.afornalik.bar.model.client parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (server.src.main.java.pl.afornalik.bar.model.client) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<server.src.main.java.pl.afornalik.bar.model.meal> meals_ =
      java.util.Collections.emptyList();
    private void ensureMealsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        meals_ = new java.util.ArrayList<server.src.main.java.pl.afornalik.bar.model.meal>(meals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        server.src.main.java.pl.afornalik.bar.model.meal, server.src.main.java.pl.afornalik.bar.model.meal.Builder, server.src.main.java.pl.afornalik.bar.model.mealOrBuilder> mealsBuilder_;

    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public java.util.List<server.src.main.java.pl.afornalik.bar.model.meal> getMealsList() {
      if (mealsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(meals_);
      } else {
        return mealsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public int getMealsCount() {
      if (mealsBuilder_ == null) {
        return meals_.size();
      } else {
        return mealsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public server.src.main.java.pl.afornalik.bar.model.meal getMeals(int index) {
      if (mealsBuilder_ == null) {
        return meals_.get(index);
      } else {
        return mealsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder setMeals(
        int index, server.src.main.java.pl.afornalik.bar.model.meal value) {
      if (mealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMealsIsMutable();
        meals_.set(index, value);
        onChanged();
      } else {
        mealsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder setMeals(
        int index, server.src.main.java.pl.afornalik.bar.model.meal.Builder builderForValue) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.set(index, builderForValue.build());
        onChanged();
      } else {
        mealsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder addMeals(server.src.main.java.pl.afornalik.bar.model.meal value) {
      if (mealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMealsIsMutable();
        meals_.add(value);
        onChanged();
      } else {
        mealsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder addMeals(
        int index, server.src.main.java.pl.afornalik.bar.model.meal value) {
      if (mealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMealsIsMutable();
        meals_.add(index, value);
        onChanged();
      } else {
        mealsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder addMeals(
        server.src.main.java.pl.afornalik.bar.model.meal.Builder builderForValue) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.add(builderForValue.build());
        onChanged();
      } else {
        mealsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder addMeals(
        int index, server.src.main.java.pl.afornalik.bar.model.meal.Builder builderForValue) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.add(index, builderForValue.build());
        onChanged();
      } else {
        mealsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder addAllMeals(
        java.lang.Iterable<? extends server.src.main.java.pl.afornalik.bar.model.meal> values) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, meals_);
        onChanged();
      } else {
        mealsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder clearMeals() {
      if (mealsBuilder_ == null) {
        meals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        mealsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public Builder removeMeals(int index) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.remove(index);
        onChanged();
      } else {
        mealsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public server.src.main.java.pl.afornalik.bar.model.meal.Builder getMealsBuilder(
        int index) {
      return getMealsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public server.src.main.java.pl.afornalik.bar.model.mealOrBuilder getMealsOrBuilder(
        int index) {
      if (mealsBuilder_ == null) {
        return meals_.get(index);  } else {
        return mealsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public java.util.List<? extends server.src.main.java.pl.afornalik.bar.model.mealOrBuilder> 
         getMealsOrBuilderList() {
      if (mealsBuilder_ != null) {
        return mealsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(meals_);
      }
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public server.src.main.java.pl.afornalik.bar.model.meal.Builder addMealsBuilder() {
      return getMealsFieldBuilder().addBuilder(
          server.src.main.java.pl.afornalik.bar.model.meal.getDefaultInstance());
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public server.src.main.java.pl.afornalik.bar.model.meal.Builder addMealsBuilder(
        int index) {
      return getMealsFieldBuilder().addBuilder(
          index, server.src.main.java.pl.afornalik.bar.model.meal.getDefaultInstance());
    }
    /**
     * <code>repeated .meal meals = 2;</code>
     */
    public java.util.List<server.src.main.java.pl.afornalik.bar.model.meal.Builder> 
         getMealsBuilderList() {
      return getMealsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        server.src.main.java.pl.afornalik.bar.model.meal, server.src.main.java.pl.afornalik.bar.model.meal.Builder, server.src.main.java.pl.afornalik.bar.model.mealOrBuilder> 
        getMealsFieldBuilder() {
      if (mealsBuilder_ == null) {
        mealsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            server.src.main.java.pl.afornalik.bar.model.meal, server.src.main.java.pl.afornalik.bar.model.meal.Builder, server.src.main.java.pl.afornalik.bar.model.mealOrBuilder>(
                meals_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        meals_ = null;
      }
      return mealsBuilder_;
    }

    private float bill_ ;
    /**
     * <code>float bill = 3;</code>
     * @return The bill.
     */
    @java.lang.Override
    public float getBill() {
      return bill_;
    }
    /**
     * <code>float bill = 3;</code>
     * @param value The bill to set.
     * @return This builder for chaining.
     */
    public Builder setBill(float value) {
      
      bill_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float bill = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBill() {
      
      bill_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client)
  }

  // @@protoc_insertion_point(class_scope:client)
  private static final server.src.main.java.pl.afornalik.bar.model.client DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new server.src.main.java.pl.afornalik.bar.model.client();
  }

  public static server.src.main.java.pl.afornalik.bar.model.client getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<client>
      PARSER = new com.google.protobuf.AbstractParser<client>() {
    @java.lang.Override
    public client parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new client(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<client> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<client> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public server.src.main.java.pl.afornalik.bar.model.client getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

