// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

public interface clientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>repeated .meal meals = 2;</code>
   */
  java.util.List<server.src.main.java.pl.afornalik.bar.model.meal> 
      getMealsList();
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  server.src.main.java.pl.afornalik.bar.model.meal getMeals(int index);
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  int getMealsCount();
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  java.util.List<? extends server.src.main.java.pl.afornalik.bar.model.mealOrBuilder> 
      getMealsOrBuilderList();
  /**
   * <code>repeated .meal meals = 2;</code>
   */
  server.src.main.java.pl.afornalik.bar.model.mealOrBuilder getMealsOrBuilder(
      int index);

  /**
   * <code>float bill = 3;</code>
   * @return The bill.
   */
  float getBill();
}
