// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

/**
 * Protobuf type {@code meal}
 */
public final class meal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meal)
    mealOrBuilder {
private static final long serialVersionUID = 0L;
  // Use meal.newBuilder() to construct.
  private meal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private meal() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new meal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private meal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 29: {

            price_ = input.readFloat();
            break;
          }
          case 32: {

            prepareTime_ = input.readInt32();
            break;
          }
          case 40: {

            deliverable_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_meal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_meal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            server.src.main.java.pl.afornalik.bar.model.meal.class, server.src.main.java.pl.afornalik.bar.model.meal.Builder.class);
  }

  /**
   * Protobuf enum {@code meal.type}
   */
  public enum type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BREAKFAST = 0;</code>
     */
    BREAKFAST(0),
    /**
     * <code>DINNER = 1;</code>
     */
    DINNER(1),
    /**
     * <code>DESSERT = 2;</code>
     */
    DESSERT(2),
    /**
     * <code>SUPPER = 3;</code>
     */
    SUPPER(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BREAKFAST = 0;</code>
     */
    public static final int BREAKFAST_VALUE = 0;
    /**
     * <code>DINNER = 1;</code>
     */
    public static final int DINNER_VALUE = 1;
    /**
     * <code>DESSERT = 2;</code>
     */
    public static final int DESSERT_VALUE = 2;
    /**
     * <code>SUPPER = 3;</code>
     */
    public static final int SUPPER_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static type forNumber(int value) {
      switch (value) {
        case 0: return BREAKFAST;
        case 1: return DINNER;
        case 2: return DESSERT;
        case 3: return SUPPER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<type>() {
            public type findValueByNumber(int number) {
              return type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return server.src.main.java.pl.afornalik.bar.model.meal.getDescriptor().getEnumTypes().get(0);
    }

    private static final type[] VALUES = values();

    public static type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:meal.type)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private float price_;
  /**
   * <code>float price = 3;</code>
   * @return The price.
   */
  @java.lang.Override
  public float getPrice() {
    return price_;
  }

  public static final int PREPARE_TIME_FIELD_NUMBER = 4;
  private int prepareTime_;
  /**
   * <code>int32 prepare_time = 4;</code>
   * @return The prepareTime.
   */
  @java.lang.Override
  public int getPrepareTime() {
    return prepareTime_;
  }

  public static final int DELIVERABLE_FIELD_NUMBER = 5;
  private boolean deliverable_;
  /**
   * <code>bool deliverable = 5;</code>
   * @return The deliverable.
   */
  @java.lang.Override
  public boolean getDeliverable() {
    return deliverable_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (price_ != 0F) {
      output.writeFloat(3, price_);
    }
    if (prepareTime_ != 0) {
      output.writeInt32(4, prepareTime_);
    }
    if (deliverable_ != false) {
      output.writeBool(5, deliverable_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (price_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, price_);
    }
    if (prepareTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, prepareTime_);
    }
    if (deliverable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, deliverable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof server.src.main.java.pl.afornalik.bar.model.meal)) {
      return super.equals(obj);
    }
    server.src.main.java.pl.afornalik.bar.model.meal other = (server.src.main.java.pl.afornalik.bar.model.meal) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (java.lang.Float.floatToIntBits(getPrice())
        != java.lang.Float.floatToIntBits(
            other.getPrice())) return false;
    if (getPrepareTime()
        != other.getPrepareTime()) return false;
    if (getDeliverable()
        != other.getDeliverable()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPrice());
    hash = (37 * hash) + PREPARE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getPrepareTime();
    hash = (37 * hash) + DELIVERABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeliverable());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static server.src.main.java.pl.afornalik.bar.model.meal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(server.src.main.java.pl.afornalik.bar.model.meal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meal)
      server.src.main.java.pl.afornalik.bar.model.mealOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_meal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_meal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.src.main.java.pl.afornalik.bar.model.meal.class, server.src.main.java.pl.afornalik.bar.model.meal.Builder.class);
    }

    // Construct using server.src.main.java.pl.afornalik.bar.model.meal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      price_ = 0F;

      prepareTime_ = 0;

      deliverable_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return server.src.main.java.pl.afornalik.bar.model.Bar.internal_static_meal_descriptor;
    }

    @java.lang.Override
    public server.src.main.java.pl.afornalik.bar.model.meal getDefaultInstanceForType() {
      return server.src.main.java.pl.afornalik.bar.model.meal.getDefaultInstance();
    }

    @java.lang.Override
    public server.src.main.java.pl.afornalik.bar.model.meal build() {
      server.src.main.java.pl.afornalik.bar.model.meal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public server.src.main.java.pl.afornalik.bar.model.meal buildPartial() {
      server.src.main.java.pl.afornalik.bar.model.meal result = new server.src.main.java.pl.afornalik.bar.model.meal(this);
      result.id_ = id_;
      result.name_ = name_;
      result.price_ = price_;
      result.prepareTime_ = prepareTime_;
      result.deliverable_ = deliverable_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof server.src.main.java.pl.afornalik.bar.model.meal) {
        return mergeFrom((server.src.main.java.pl.afornalik.bar.model.meal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(server.src.main.java.pl.afornalik.bar.model.meal other) {
      if (other == server.src.main.java.pl.afornalik.bar.model.meal.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getPrice() != 0F) {
        setPrice(other.getPrice());
      }
      if (other.getPrepareTime() != 0) {
        setPrepareTime(other.getPrepareTime());
      }
      if (other.getDeliverable() != false) {
        setDeliverable(other.getDeliverable());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      server.src.main.java.pl.afornalik.bar.model.meal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (server.src.main.java.pl.afornalik.bar.model.meal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private float price_ ;
    /**
     * <code>float price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public float getPrice() {
      return price_;
    }
    /**
     * <code>float price = 3;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(float value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0F;
      onChanged();
      return this;
    }

    private int prepareTime_ ;
    /**
     * <code>int32 prepare_time = 4;</code>
     * @return The prepareTime.
     */
    @java.lang.Override
    public int getPrepareTime() {
      return prepareTime_;
    }
    /**
     * <code>int32 prepare_time = 4;</code>
     * @param value The prepareTime to set.
     * @return This builder for chaining.
     */
    public Builder setPrepareTime(int value) {
      
      prepareTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prepare_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrepareTime() {
      
      prepareTime_ = 0;
      onChanged();
      return this;
    }

    private boolean deliverable_ ;
    /**
     * <code>bool deliverable = 5;</code>
     * @return The deliverable.
     */
    @java.lang.Override
    public boolean getDeliverable() {
      return deliverable_;
    }
    /**
     * <code>bool deliverable = 5;</code>
     * @param value The deliverable to set.
     * @return This builder for chaining.
     */
    public Builder setDeliverable(boolean value) {
      
      deliverable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool deliverable = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliverable() {
      
      deliverable_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meal)
  }

  // @@protoc_insertion_point(class_scope:meal)
  private static final server.src.main.java.pl.afornalik.bar.model.meal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new server.src.main.java.pl.afornalik.bar.model.meal();
  }

  public static server.src.main.java.pl.afornalik.bar.model.meal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<meal>
      PARSER = new com.google.protobuf.AbstractParser<meal>() {
    @java.lang.Override
    public meal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new meal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<meal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<meal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public server.src.main.java.pl.afornalik.bar.model.meal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

