// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

public interface waiterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waiter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .client clients = 3;</code>
   */
  java.util.List<server.src.main.java.pl.afornalik.bar.model.client> 
      getClientsList();
  /**
   * <code>repeated .client clients = 3;</code>
   */
  server.src.main.java.pl.afornalik.bar.model.client getClients(int index);
  /**
   * <code>repeated .client clients = 3;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .client clients = 3;</code>
   */
  java.util.List<? extends server.src.main.java.pl.afornalik.bar.model.clientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .client clients = 3;</code>
   */
  server.src.main.java.pl.afornalik.bar.model.clientOrBuilder getClientsOrBuilder(
      int index);
}
