// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pl.afornalik.bar.model.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>repeated .pl.afornalik.bar.model.Meal meals = 2;</code>
   */
  java.util.List<pl.afornalik.bar.model.Meal> 
      getMealsList();
  /**
   * <code>repeated .pl.afornalik.bar.model.Meal meals = 2;</code>
   */
  pl.afornalik.bar.model.Meal getMeals(int index);
  /**
   * <code>repeated .pl.afornalik.bar.model.Meal meals = 2;</code>
   */
  int getMealsCount();
  /**
   * <code>repeated .pl.afornalik.bar.model.Meal meals = 2;</code>
   */
  java.util.List<? extends pl.afornalik.bar.model.MealOrBuilder> 
      getMealsOrBuilderList();
  /**
   * <code>repeated .pl.afornalik.bar.model.Meal meals = 2;</code>
   */
  pl.afornalik.bar.model.MealOrBuilder getMealsOrBuilder(
      int index);

  /**
   * <code>optional float bill = 3;</code>
   */
  float getBill();
}
