// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

/**
 * Protobuf type {@code pl.afornalik.bar.model.Meal}
 */
public  final class Meal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pl.afornalik.bar.model.Meal)
    MealOrBuilder {
  // Use Meal.newBuilder() to construct.
  private Meal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Meal() {
    id_ = 0;
    name_ = "";
    price_ = 0F;
    prepareTime_ = 0;
    deliverable_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Meal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 29: {

            price_ = input.readFloat();
            break;
          }
          case 32: {

            prepareTime_ = input.readInt32();
            break;
          }
          case 40: {

            deliverable_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pl.afornalik.bar.model.Bar.internal_static_pl_afornalik_bar_model_Meal_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pl.afornalik.bar.model.Bar.internal_static_pl_afornalik_bar_model_Meal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pl.afornalik.bar.model.Meal.class, pl.afornalik.bar.model.Meal.Builder.class);
  }

  /**
   * Protobuf enum {@code pl.afornalik.bar.model.Meal.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BREAKFAST = 0;</code>
     */
    BREAKFAST(0),
    /**
     * <code>DINNER = 1;</code>
     */
    DINNER(1),
    /**
     * <code>DESSERT = 2;</code>
     */
    DESSERT(2),
    /**
     * <code>SUPPER = 3;</code>
     */
    SUPPER(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BREAKFAST = 0;</code>
     */
    public static final int BREAKFAST_VALUE = 0;
    /**
     * <code>DINNER = 1;</code>
     */
    public static final int DINNER_VALUE = 1;
    /**
     * <code>DESSERT = 2;</code>
     */
    public static final int DESSERT_VALUE = 2;
    /**
     * <code>SUPPER = 3;</code>
     */
    public static final int SUPPER_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return BREAKFAST;
        case 1: return DINNER;
        case 2: return DESSERT;
        case 3: return SUPPER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pl.afornalik.bar.model.Meal.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pl.afornalik.bar.model.Meal.Type)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private float price_;
  /**
   * <code>optional float price = 3;</code>
   */
  public float getPrice() {
    return price_;
  }

  public static final int PREPARE_TIME_FIELD_NUMBER = 4;
  private int prepareTime_;
  /**
   * <code>optional int32 prepare_time = 4;</code>
   */
  public int getPrepareTime() {
    return prepareTime_;
  }

  public static final int DELIVERABLE_FIELD_NUMBER = 5;
  private boolean deliverable_;
  /**
   * <code>optional bool deliverable = 5;</code>
   */
  public boolean getDeliverable() {
    return deliverable_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (price_ != 0F) {
      output.writeFloat(3, price_);
    }
    if (prepareTime_ != 0) {
      output.writeInt32(4, prepareTime_);
    }
    if (deliverable_ != false) {
      output.writeBool(5, deliverable_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (price_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, price_);
    }
    if (prepareTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, prepareTime_);
    }
    if (deliverable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, deliverable_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pl.afornalik.bar.model.Meal)) {
      return super.equals(obj);
    }
    pl.afornalik.bar.model.Meal other = (pl.afornalik.bar.model.Meal) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && (
        java.lang.Float.floatToIntBits(getPrice())
        == java.lang.Float.floatToIntBits(
            other.getPrice()));
    result = result && (getPrepareTime()
        == other.getPrepareTime());
    result = result && (getDeliverable()
        == other.getDeliverable());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPrice());
    hash = (37 * hash) + PREPARE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getPrepareTime();
    hash = (37 * hash) + DELIVERABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeliverable());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pl.afornalik.bar.model.Meal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pl.afornalik.bar.model.Meal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pl.afornalik.bar.model.Meal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pl.afornalik.bar.model.Meal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pl.afornalik.bar.model.Meal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pl.afornalik.bar.model.Meal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pl.afornalik.bar.model.Meal)
      pl.afornalik.bar.model.MealOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.afornalik.bar.model.Bar.internal_static_pl_afornalik_bar_model_Meal_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.afornalik.bar.model.Bar.internal_static_pl_afornalik_bar_model_Meal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.afornalik.bar.model.Meal.class, pl.afornalik.bar.model.Meal.Builder.class);
    }

    // Construct using pl.afornalik.bar.model.Meal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      price_ = 0F;

      prepareTime_ = 0;

      deliverable_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pl.afornalik.bar.model.Bar.internal_static_pl_afornalik_bar_model_Meal_descriptor;
    }

    public pl.afornalik.bar.model.Meal getDefaultInstanceForType() {
      return pl.afornalik.bar.model.Meal.getDefaultInstance();
    }

    public pl.afornalik.bar.model.Meal build() {
      pl.afornalik.bar.model.Meal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public pl.afornalik.bar.model.Meal buildPartial() {
      pl.afornalik.bar.model.Meal result = new pl.afornalik.bar.model.Meal(this);
      result.id_ = id_;
      result.name_ = name_;
      result.price_ = price_;
      result.prepareTime_ = prepareTime_;
      result.deliverable_ = deliverable_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pl.afornalik.bar.model.Meal) {
        return mergeFrom((pl.afornalik.bar.model.Meal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pl.afornalik.bar.model.Meal other) {
      if (other == pl.afornalik.bar.model.Meal.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getPrice() != 0F) {
        setPrice(other.getPrice());
      }
      if (other.getPrepareTime() != 0) {
        setPrepareTime(other.getPrepareTime());
      }
      if (other.getDeliverable() != false) {
        setDeliverable(other.getDeliverable());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pl.afornalik.bar.model.Meal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pl.afornalik.bar.model.Meal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private float price_ ;
    /**
     * <code>optional float price = 3;</code>
     */
    public float getPrice() {
      return price_;
    }
    /**
     * <code>optional float price = 3;</code>
     */
    public Builder setPrice(float value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float price = 3;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0F;
      onChanged();
      return this;
    }

    private int prepareTime_ ;
    /**
     * <code>optional int32 prepare_time = 4;</code>
     */
    public int getPrepareTime() {
      return prepareTime_;
    }
    /**
     * <code>optional int32 prepare_time = 4;</code>
     */
    public Builder setPrepareTime(int value) {
      
      prepareTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 prepare_time = 4;</code>
     */
    public Builder clearPrepareTime() {
      
      prepareTime_ = 0;
      onChanged();
      return this;
    }

    private boolean deliverable_ ;
    /**
     * <code>optional bool deliverable = 5;</code>
     */
    public boolean getDeliverable() {
      return deliverable_;
    }
    /**
     * <code>optional bool deliverable = 5;</code>
     */
    public Builder setDeliverable(boolean value) {
      
      deliverable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool deliverable = 5;</code>
     */
    public Builder clearDeliverable() {
      
      deliverable_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:pl.afornalik.bar.model.Meal)
  }

  // @@protoc_insertion_point(class_scope:pl.afornalik.bar.model.Meal)
  private static final pl.afornalik.bar.model.Meal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pl.afornalik.bar.model.Meal();
  }

  public static pl.afornalik.bar.model.Meal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Meal>
      PARSER = new com.google.protobuf.AbstractParser<Meal>() {
    public Meal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Meal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Meal> getParserForType() {
    return PARSER;
  }

  public pl.afornalik.bar.model.Meal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

