// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

package pl.afornalik.bar.model;

public interface WaiterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pl.afornalik.bar.model.Waiter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .pl.afornalik.bar.model.Client clients = 3;</code>
   */
  java.util.List<pl.afornalik.bar.model.Client> 
      getClientsList();
  /**
   * <code>repeated .pl.afornalik.bar.model.Client clients = 3;</code>
   */
  pl.afornalik.bar.model.Client getClients(int index);
  /**
   * <code>repeated .pl.afornalik.bar.model.Client clients = 3;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .pl.afornalik.bar.model.Client clients = 3;</code>
   */
  java.util.List<? extends pl.afornalik.bar.model.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .pl.afornalik.bar.model.Client clients = 3;</code>
   */
  pl.afornalik.bar.model.ClientOrBuilder getClientsOrBuilder(
      int index);
}
